// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCccJ-zokmACCyhVQaSB84y5YL98aaD23w',
    appId: '1:655174886630:web:c5935617547e7683b50727',
    messagingSenderId: '655174886630',
    projectId: 'ela-book',
    authDomain: 'ela-book.firebaseapp.com',
    storageBucket: 'ela-book.firebasestorage.app',
    measurementId: 'G-PBL8ZB8PC4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4eCa4Z0_5Nc4xf4gnPnLmX8G0BiseAXQ',
    appId: '1:655174886630:android:dacffbe63ae425d6b50727',
    messagingSenderId: '655174886630',
    projectId: 'ela-book',
    storageBucket: 'ela-book.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDjj8fGgPgnzx2ZTyxFSw523MoFx1eJew',
    appId: '1:655174886630:ios:a6cb6ab7a79e9294b50727',
    messagingSenderId: '655174886630',
    projectId: 'ela-book',
    storageBucket: 'ela-book.firebasestorage.app',
    iosBundleId: 'com.example.elaBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDjj8fGgPgnzx2ZTyxFSw523MoFx1eJew',
    appId: '1:655174886630:ios:a6cb6ab7a79e9294b50727',
    messagingSenderId: '655174886630',
    projectId: 'ela-book',
    storageBucket: 'ela-book.firebasestorage.app',
    iosBundleId: 'com.example.elaBook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCccJ-zokmACCyhVQaSB84y5YL98aaD23w',
    appId: '1:655174886630:web:78c0000e7869d196b50727',
    messagingSenderId: '655174886630',
    projectId: 'ela-book',
    authDomain: 'ela-book.firebaseapp.com',
    storageBucket: 'ela-book.firebasestorage.app',
    measurementId: 'G-6VQ0HQ6W8B',
  );
}
